markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Site settings
title: Writer Theme
email: help@writer-theme.com
description: > # Writer Theme is a responsive template
 focussed on typography, minimal design and
  quality photography built using the Jekyll platform.
baseurl: "/sgarbesi" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author', 'fa-user']
single_footer: '<p>The writer community loves your content. Writer &copy; 2016 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Writer: ['Writer 2016', '/about']

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author_name : Salvatore Garbesi
      author_url : /author
      author_gravatar: https://www.gravatar.com/avatar/4bcecfcba5fbc6c281564f9b62903acd?s=200&.jpg
      show_avatar : true
      show_related_posts: true


# Build settings
# markdown: kramdown
